package com.ganjianping.lab.ak.common.theme

import androidx.compose.ui.graphics.Color

val SlateBlack = Color(0xFF000000)
val SlateWhite = Color(0xFFFFFFFF)
val SlateNeutral = Color(0xFFE8E8E8)
val SlateWarmCanvas = Color(0xFFFFFCF8)

val SlateLightSecondary = Color(0xFF4A4A4A)
val SlateLightOnSecondaryContainer = Color(0xFF1B1B1B)
val SlateLightTertiary = Color(0xFF5C5C5C)
val SlateLightSurface = Color(0xFFFFFFFF)
val SlateLightSurfaceDim = Color(0xFFDADADA)
val SlateLightSurfaceContainerLow = Color(0xFFF7F7F7)
val SlateLightSurfaceContainer = Color(0xFFF1F1F1)
val SlateLightSurfaceContainerHigh = Color(0xFFEBEBEB)
val SlateLightSurfaceContainerHighest = Color(0xFFE3E3E3)
val SlateLightOnSurface = Color(0xFF1A1A1A)
val SlateLightOnSurfaceVariant = Color(0xFF474747)
val SlateLightOutline = Color(0xFF747474)
val SlateLightOutlineVariant = Color(0xFFC6C6C6)

val SlateDarkBackground = Color(0xFF0D0D0D)
val SlateDarkPrimaryContainer = Color(0xFF343434)
val SlateDarkSecondary = Color(0xFFC9C9C9)
val SlateDarkSecondaryContainer = Color(0xFF3A3A3A)
val SlateDarkTertiary = Color(0xFFE0E0E0)
val SlateDarkTertiaryContainer = Color(0xFF424242)
val SlateDarkSurfaceDim = Color(0xFF0D0D0D)
val SlateDarkSurface = Color(0xFF151515)
val SlateDarkSurfaceContainerLow = Color(0xFF1B1B1B)
val SlateDarkSurfaceContainer = Color(0xFF222222)
val SlateDarkSurfaceContainerHigh = Color(0xFF292929)
val SlateDarkSurfaceContainerHighest = Color(0xFF303030)
val SlateDarkOnSurface = Color(0xFFE8E8E8)
val SlateDarkOnSurfaceVariant = Color(0xFFC6C6C6)
val SlateDarkOutline = Color(0xFF919191)
val SlateDarkOutlineVariant = Color(0xFF474747)

val SlateError = Color(0xFFBA1A1A)
val SlateOnError = Color(0xFFFFFFFF)
val SlateErrorContainer = Color(0xFFFFDAD6)
val SlateOnErrorContainer = Color(0xFF410002)
val SlateDarkError = Color(0xFFFFB4AB)
val SlateDarkOnError = Color(0xFF690005)
val SlateDarkErrorContainer = Color(0xFF93000A)
val SlateDarkOnErrorContainer = Color(0xFFFFDAD6)
